baseURL = "https://braindump.matiashernandez.dev/"
languageCode = "es-es"
title = "Mis notas - Matias Hernández"
theme = "cortex"
googleAnalytics = "UA-45569809-3"
[params]
email = "hola@matiashernandez.dev"
footer = "Icon by Freepik. Built with ♥ with Org-mode and Hugo. Thanks to <a href=\"https://github.com/jethrokuan/braindump\">Jethro Kuan</a>"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
